export const TOGGLE_STARTING_PAGE = 'TOGGLE_STARTING_PAGE'
export const GET_ALL_INVITATIONS = 'GET_ALL_INVITATIONS'
export const GET_INVITATION = 'GET_INVITATION'
export const ADD_INVITATION = 'ADD_INVITATION'
